# Generated by Django 6.0.3 on 2026-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulldegree', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=200)),
                ('vname', models.CharField(max_length=100)),
                ('subject', models.JSONField(default=list)),
                ('text', models.TextField()),
                ('degree', models.CharField(max_length=10)),
                ('interested', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/imange/')),
                ('complete', models.CharField(max_length=200)),
                ('no', models.CharField(default='01', max_length=2)),
                ('fullname', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('tech', models.JSONField(default=list)),
                ('link', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default='01', max_length=2)),
                ('shortname', models.CharField(max_length=5)),
                ('fullname', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
